Repository UKHSA-Internal/coronavirus-dashboard, pull requests merged in 2020-06, with the labels that each got.

#179 Adds announcement
  package.json
  src/components/Announcement/Announcement.style.js
  src/pages/Regional/Regional.js
Labels: documentation

#178 Sass components
  src/index.scss
  src/sass/_accessibility.scss
  src/sass/_base-elements.scss
  src/sass/_cookie-banner.scss
  src/sass/_day-picker.scss
  src/sass/_govuk-extensions.scss
  src/sass/_layout.scss
  src/sass/_markdown.scss
  src/sass/_side-navigation.scss
  src/sass/_sticky-header.scss
Labels: dependencies, enhancement

#181 card headers simplified. flex utility classes added.
  src/components/Card/Card.js
  src/index.scss
  src/pages/DailySummary/DailySummary.styles.js
  src/sass/_utility.scss
Labels: enhancement

#180 Dashboard and simple layouts
  src/App.js
  src/index.scss
  src/sass/_dashboard.scss
Labels: enhancement

#182 Mobile nav
  src/App.js
  src/components/SideNavMobile/SideNavMobile.js
  src/components/SideNavMobile/SideNavMobile.styles.js
  src/components/SideNavMobile/SideNavMobile.types.js
  src/components/SideNavMobile/index.js
  src/components/SideNavigation/SideNavigation.js
  src/sass/_dashboard.scss
  src/sass/_layout.scss
  src/sass/_side-navigation.scss
Labels: enhancement

#183 Tabs
  src/components/Card/Card.js
  src/components/Card/Card.styles.js
  src/components/TabLink/TabLink.js
  src/components/TabLink/TabLink.styles.js
  src/pages/Cases/Cases.js
  src/sass/_utility.scss
Labels: enhancement

#191 Updates the number description
  package.json
  src/pages/Regional/Regional.js
Labels: Correction
