Repository UKHSA-Internal/coronavirus-dashboard, pull requests merged in 2020-05, with the labels that each got.

#133 Fixes disordered charts when toggling to tables & back
  src/components/BarChart/BarChart.js
  src/components/ChartTable/ChartTable.js
  src/components/ChartTable/Charts.js
  src/components/LineChart/LineChart.js
  src/components/StackedBarChart/StackedBarChart.js
Labels: bug

#136 Essential updates
  package.json
  src/components/BarChart/BarChart.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/ChartTable.js
  src/components/ChartTable/Charts.js
  src/components/LineChart/LineChart.js
  src/components/StackedBarChart/StackedBarChart.js
  src/index.scss
  src/pages/Accessibility/Accessibility.js
  src/pages/Accessibility/Accessibility.styles.js
  src/pages/Accessibility/Accessibility.types.js
  src/pages/Archive/Archive.js
Labels: accessibility, bug, enhancement

#141 Minor updates
  package.json
  src/components/ChartTable/ChartTable.js
  src/components/ChartTable/Charts.js
  src/components/ChartTable/Tables.js
  src/pages/Regional/Regional.js
Labels: Correction, enhancement

#144 Minor fixes
  .github/workflows/development_covid19-test-dashboard.yml
  .github/workflows/master_covid19static.yml
  package.json
  src/pages/Regional/Regional.js
Labels: Correction

#143 Set role="main" on main content of each page
  src/pages/About/About.js
  src/pages/Accessibility/Accessibility.js
  src/pages/Archive/Archive.js
  src/pages/Archive/Archive.style.js
  src/pages/Cookies/Cookies.js
  src/pages/MobileRegionTable/MobileRegionTable.js
  src/pages/MobileRegionTable/MobileRegionTable.styles.js
  src/pages/Regional/Regional.js
  src/pages/Regional/Regional.styles.js
Labels: accessibility

#142 Add aria-label to the map canvas
  src/components/Map/Map.js
Labels: accessibility

#139 Improve line graph display on mobile
  src/components/BarChart/BarChart.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/LineChart/LineChart.js
  src/components/StackedBarChart/StackedBarChart.js
Labels: accessibility, enhancement

#135 Add 'Back to top' links to main and about pages
  public/index.html
  src/App.js
  src/components/BackToTop/BackToTop.js
  src/components/BackToTop/BackToTop.styles.js
  src/components/BackToTop/BackToTop.types.js
  src/components/BackToTop/index.js
  src/hooks/useBackToTopOverlayVisible.js
  src/index.js
  src/index.scss
  src/pages/About/About.styles.js
  src/pages/Regional/Regional.styles.js
Labels: accessibility, enhancement

#156 Essentials updates and improvements
  package.json
  public/index.html
  src/App.js
  src/components/BackToTop/BackToTop.js
  src/components/BackToTop/BackToTop.styles.js
  src/components/BackToTop/BackToTop.types.js
  src/components/BackToTop/index.js
  src/components/BarChart/BarChart.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/ChartTable.types.js
  src/components/ChartTable/Tables.js
  src/components/LineChart/LineChart.js
  src/components/Map/Map.js
  src/components/StackedBarChart/StackedBarChart.js
  src/hooks/useBackToTopOverlayVisible.js
  src/index.js
  src/index.scss
  src/pages/About/About.js
  src/pages/About/About.styles.js
  src/pages/Accessibility/Accessibility.js
  src/pages/Archive/Archive.js
  src/pages/Archive/Archive.style.js
  src/pages/Cookies/Cookies.js
  src/pages/MobileRegionTable/MobileRegionTable.js
  src/pages/MobileRegionTable/MobileRegionTable.styles.js
  src/pages/Regional/Regional.js
  src/pages/Regional/Regional.styles.js
  src/pages/Regional/Regional.types.js
  types/Data.js
  yarn.lock
Labels: accessibility, bug, enhancement

#155 Integrates rate and adds LTLA data
  src/App.js
  src/components/Export/Export.styles.js
  src/components/Map/Map.js
  src/components/Map/Map.styles.js
  src/components/Map/Map.types.js
  src/components/Map/countryLayer.js
  src/components/Map/index.js
  src/components/Map/regionLayer.js
  src/components/Map/utlaLayer.js
  src/components/Map/zoomLayers.js
  src/components/MapTable/Map.js
  src/components/MapTable/MapTable.js
  src/components/MapTable/MapTable.styles.js
  src/components/MapTable/MapTable.types.js
  src/components/MapTable/Table.js
  src/components/MapTable/constants.js
  src/components/MapTable/index.js
  src/components/MapTable/utils.js
  src/components/RegionTable/RegionTable.js
  src/components/RegionTable/RegionTable.styles.js
  src/components/RegionTable/RegionTable.types.js
  src/components/RegionTable/index.js
  src/pages/MobileRegionTable/MobileRegionTable.js
  src/pages/Regional/Regional.js
Labels: enhancement

#157 Big Numbers + Small Numbers
  src/components/BigNumber/BigNumber.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/BigNumber/index.js
  src/components/MapTable/MapTable.styles.js
  src/components/SmallNumber/SmallNumber.js
  src/components/SmallNumber/SmallNumber.styles.js
  src/components/SmallNumber/SmallNumber.types.js
  src/components/SmallNumber/index.js
  src/pages/Regional/Regional.js
Labels: accessibility, enhancement

#159 New features and essential updates
  README.md
  package.json
  src/App.js
  src/components/BackToTop/BackToTop.js
  src/components/BackToTop/BackToTop.styles.js
  src/components/BigNumber/BigNumber.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/BigNumber/index.js
  src/components/Disclaimer/Disclaimer.js
  src/components/Disclaimer/Disclaimer.styles.js
  src/components/Export/Export.js
  src/components/Export/Export.styles.js
  src/components/Map/Map.js
  src/components/Map/Map.styles.js
  src/components/Map/Map.types.js
  src/components/Map/countryLayer.js
  src/components/Map/index.js
  src/components/Map/regionLayer.js
  src/components/Map/utlaLayer.js
  src/components/Map/zoomLayers.js
  src/components/MapTable/Map.js
  src/components/MapTable/MapTable.js
  src/components/MapTable/MapTable.styles.js
  src/components/MapTable/MapTable.types.js
  src/components/MapTable/Table.js
  src/components/MapTable/constants.js
  src/components/MapTable/index.js
  src/components/MapTable/utils.js
  src/components/RegionTable/RegionTable.js
  src/components/RegionTable/RegionTable.styles.js
  src/components/RegionTable/RegionTable.types.js
  src/components/RegionTable/index.js
  src/components/SmallNumber/SmallNumber.js
  src/components/SmallNumber/SmallNumber.styles.js
  src/components/SmallNumber/SmallNumber.types.js
  src/components/SmallNumber/index.js
  src/index.scss
  src/pages/MobileRegionTable/MobileRegionTable.js
  src/pages/Regional/Regional.js
Labels: accessibility, bug, enhancement

#160 Rolling average
  src/common/utils.js
  src/components/BarChart/BarChart.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/Charts.js
  src/components/LineChart/LineChart.js
  src/components/StackedBarChart/StackedBarChart.js
Labels: enhancement

#161 New data structure
  src/hooks/useLoadData.js
  src/pages/Regional/Regional.js
Labels: enhancement

#163 Map style assets
  .env.development
  package.json
  scripts/patchUrls.js
  src/components/MapTable/Map.js
  src/hooks/useLoadData.js
  yarn.lock
Labels: enhancement

#166 New feature and essential updates
  package.json
  src/components/BarChart/BarChart.js
  src/components/StackedBarChart/StackedBarChart.js
  src/pages/About/About.js
  src/pages/Accessibility/Accessibility.js
  src/pages/Archive/Archive.js
  src/pages/Cookies/Cookies.js
  src/pages/MobileRegionTable/MobileRegionTable.js
Labels: bug, enhancement

#169 Layout alignment
  src/components/AltChartTable/AltChartTable.js
  src/components/BigNumber/BigNumber.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/Tables.js
  src/components/Disclaimer/Disclaimer.js
  src/components/LineChart/LineChart.js
  src/components/MapTable/MapTable.js
  src/components/PageTitle/PageTitle.js
  src/components/PageTitle/PageTitle.styles.js
  src/components/SmallNumber/SmallNumber.js
  src/components/StackedBarChart/StackedBarChart.js
  src/components/ViewAs/ViewAs.js
  src/index.scss
  src/pages/About/About.js
  src/pages/About/About.styles.js
  src/pages/Accessibility/Accessibility.js
  src/pages/Accessibility/Accessibility.styles.js
  src/pages/Archive/Archive.js
  src/pages/Archive/Archive.style.js
  src/pages/Cookies/Cookies.js
  src/pages/Cookies/Cookies.styles.js
  src/pages/MobileRegionTable/MobileRegionTable.js
  src/pages/MobileRegionTable/MobileRegionTable.styles.js
  src/pages/Regional/Regional.js
  src/pages/Regional/Regional.styles.js
Labels: enhancement

#171 Error boundary
  package.json
  src/App.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/ErrorBoundary/ErrorBoundary.styles.js
  src/components/ErrorBoundary/ErrorBoundary.types.js
  src/components/MapTable/Map.js
Labels: enhancement

#172 Archives fix
  src/pages/About/About.js
  src/pages/Archive/Archive.js
Labels: bug

#173 Essential updates and general improvements
  package.json
  src/App.js
  src/components/AltChartTable/AltChartTable.js
  src/components/BarChart/BarChart.js
  src/components/BigNumber/BigNumber.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/Tables.js
  src/components/Disclaimer/Disclaimer.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/ErrorBoundary/ErrorBoundary.styles.js
  src/components/ErrorBoundary/ErrorBoundary.types.js
  src/components/LineChart/LineChart.js
  src/components/MapTable/Map.js
  src/components/MapTable/MapTable.js
  src/components/PageTitle/PageTitle.js
  src/components/PageTitle/PageTitle.styles.js
  src/components/SmallNumber/SmallNumber.js
  src/components/StackedBarChart/StackedBarChart.js
  src/components/ViewAs/ViewAs.js
  src/index.scss
  src/pages/About/About.js
  src/pages/About/About.styles.js
  src/pages/Accessibility/Accessibility.js
  src/pages/Accessibility/Accessibility.styles.js
  src/pages/Archive/Archive.js
  src/pages/Archive/Archive.style.js
  src/pages/Cookies/Cookies.js
  src/pages/Cookies/Cookies.styles.js
  src/pages/MobileRegionTable/MobileRegionTable.js
  src/pages/MobileRegionTable/MobileRegionTable.styles.js
  src/pages/Regional/Regional.js
  src/pages/Regional/Regional.styles.js
Labels: accessibility, bug, enhancement

#174 Correct the download path
  src/pages/Archive/Archive.js
Labels: bug

#175 Download links in the archives
  package.json
  src/pages/Archive/Archive.js
Labels: bug

#176 Adjustment to the moving average
  package.json
  src/components/StackedBarChart/StackedBarChart.js
Labels: Correction

#177 Major developments
  .github/workflows/development_covid19-test-dashboard.yml
  package.json
  src/App.js
  src/common/urls.js
  src/components/BigNumber/BigNumber.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/Card/Card.js
  src/components/Card/Card.styles.js
  src/components/Card/Card.types.js
  src/components/Card/index.js
  src/components/DashboardHeader/DashboardHeader.js
  src/components/DashboardHeader/DashboardHeader.styles.js
  src/components/DashboardHeader/DashboardHeader.types.js
  src/components/DashboardHeader/index.js
  src/components/SideNavigation/SideNavigation.js
  src/components/SideNavigation/SideNavigation.styles.js
  src/components/SideNavigation/SideNavigation.types.js
  src/components/SideNavigation/index.js
  src/components/StackedBarChart/StackedBarChart.js
  src/hooks/useLoadData.js
  src/index.scss
  src/pages/Archive/Archive.js
  src/pages/Cases/Cases.js
  src/pages/Cases/Cases.styles.js
  src/pages/Cases/Cases.types.js
  src/pages/Cases/index.js
  src/pages/DailySummary/DailySummary.js
  src/pages/DailySummary/DailySummary.styles.js
  src/pages/DailySummary/DailySummary.types.js
  src/pages/DailySummary/index.js
  src/pages/Deaths/Deaths.js
  src/pages/Deaths/Deaths.styles.js
  src/pages/Deaths/Deaths.types.js
  src/pages/Deaths/index.js
  src/pages/Healthcare/Healthcare.js
  src/pages/Healthcare/Healthcare.styles.js
  src/pages/Healthcare/Healthcare.types.js
  src/pages/Healthcare/index.js
  src/pages/Tests/Tests.js
  src/pages/Tests/Tests.styles.js
  src/pages/Tests/Tests.types.js
  src/pages/Tests/index.js
  yarn.lock
Labels: enhancement
