Repository UKHSA-Internal/coronavirus-dashboard, pull requests merged in 2020-12, with the labels that each got.

#267 Bookmark about page
  src/App.js
  src/components/BrowserHistory/BrowserHistory.js
  src/components/BrowserHistory/BrowserHistory.styles.js
  src/components/BrowserHistory/index.js
  src/hooks/useGenericAPI.js
  src/pages/About/About.js
  src/pages/About/About.types.js
Labels: accessibility, enhancement

#256 Fix documentation typo
  src/pages/ApiDocs/QueryParameters/Structure.js
Labels: Correction

#268 Update govuk-react-jsx to 4.0.3 and add react-helmet to satisfy peer dependency
  package.json
  yarn.lock
Labels: dependencies
