Repository UKHSA-Internal/coronavirus-dashboard, pull requests merged in 2020-04, with the labels that each got.

#5 CSV Export service.
  src/components/Export/Export.js
  src/components/Export/Export.styles.js
  src/components/Export/Export.types.js
  src/components/Export/Export.utils.js
  src/components/Export/index.js
  src/pages/Regional/Regional.js
Labels: enhancement

#39 Static downloads
  src/components/Export/Export.js
  src/components/Export/Export.types.js
  src/components/Export/Export.utils.js
  src/components/Export/index.js
  src/pages/Regional/Regional.js
Labels: enhancement

#34 Add min and max zoom to the map, improve default centroid/zoom
  src/components/Map/Map.js
Labels: enhancement

#45 Essential improvements and new features
  package.json
  src/components/Export/Export.js
  src/components/Export/Export.types.js
  src/components/Export/Export.utils.js
  src/components/Export/index.js
  src/components/Map/Map.js
  src/pages/Regional/Regional.js
Labels: enhancement

#47 Cookie preferences
  public/web.config
  src/App.js
  src/components/CookieBanner/CookieBanner.js
  src/index.scss
  src/pages/About/About.js
  src/pages/Cookies/Cookies.js
  src/pages/Cookies/Cookies.styles.js
  src/pages/Cookies/Cookies.types.js
  src/pages/Cookies/index.js
Labels: enhancement

#50 Downloads
  public/web.config
  src/components/Export/Export.js
  src/components/Export/Export.styles.js
  src/pages/Regional/Regional.js
Labels: enhancement

#52 Data source and timestamp
  package.json
  src/hooks/useLoadData.js
  src/pages/Regional/Regional.js
  yarn.lock
Labels: enhancement

#54 Include json download count
  src/components/Export/Export.js
  src/components/Navigation/Navigation.js
Labels: enhancement

#53 Base circle radius scales at 0 cases and 0 pixels
  src/components/Map/countryLayer.js
  src/components/Map/regionLayer.js
  src/components/Map/utlaLayer.js
Labels: enhancement

#42 Make table headers sticky.
  src/index.scss
Labels: enhancement

#57 Sticky table heads
  src/components/RegionTable/RegionTable.js
  src/index.scss
  yarn.lock
Labels: enhancement

#58 Cookie preferences
  src/components/CookieBanner/CookieBanner.js
  src/pages/Cookies/Cookies.js
Labels: bug

#61 Major updates
  .github/workflows/build_test.yml
  package.json
  public/web.config
  src/App.js
  src/components/CookieBanner/CookieBanner.js
  src/components/Export/Export.js
  src/components/Export/Export.styles.js
  src/components/Map/countryLayer.js
  src/components/Map/regionLayer.js
  src/components/Map/utlaLayer.js
  src/components/Navigation/Navigation.js
  src/components/RegionTable/RegionTable.js
  src/hooks/useLoadData.js
  src/index.scss
  src/pages/About/About.js
  src/pages/Cookies/Cookies.js
  src/pages/Cookies/Cookies.styles.js
  src/pages/Cookies/Cookies.types.js
  src/pages/Cookies/index.js
  src/pages/Regional/Regional.js
  yarn.lock
Labels: Correction, bug, dependencies, enhancement

#65 Update About.js
  src/pages/About/About.js
Labels: documentation, enhancement

#66 Update About.js
  src/pages/About/About.js
Labels: Correction, documentation

#68 IE fixes
  src/addIECss.js
  src/components/AltChartTable/AltChartTable.styles.js
  src/components/BarChart/BarChart.styles.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/ChartTable/ChartTable.styles.js
  src/components/LineChart/LineChart.styles.js
  src/components/Map/Map.styles.js
  src/components/PageTitle/PageTitle.styles.js
  src/components/RegionTable/RegionTable.styles.js
  src/components/StackedBarChart/StackedBarChart.styles.js
  src/components/ViewAs/ViewAs.styles.js
  src/index.js
  src/index.scss
  src/isIE.js
  src/pages/Regional/Regional.js
  src/pages/Regional/Regional.styles.js
Labels: bug, enhancement

#63 Fail more gracefully on WebGL error
  src/components/Map/Map.js
Labels: bug, enhancement

#70 Essential updates
  package.json
  src/addIECss.js
  src/components/AltChartTable/AltChartTable.styles.js
  src/components/BarChart/BarChart.styles.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/ChartTable/ChartTable.styles.js
  src/components/Export/Export.js
  src/components/LineChart/LineChart.styles.js
  src/components/Map/Map.js
  src/components/Map/Map.styles.js
  src/components/PageTitle/PageTitle.styles.js
  src/components/RegionTable/RegionTable.styles.js
  src/components/StackedBarChart/StackedBarChart.styles.js
  src/components/ViewAs/ViewAs.styles.js
  src/index.js
  src/index.scss
  src/isIE.js
  src/pages/Regional/Regional.js
  src/pages/Regional/Regional.styles.js
Labels: bug, enhancement

#72 Stacked bar chart and table inconsistency
  package.json
  src/components/ChartTable/Charts.js
  types/Data.js
Labels: bug

#73 Increases width of charts / tables on IE
  src/components/BarChart/BarChart.styles.js
  src/components/ChartTable/ChartTable.styles.js
  src/components/LineChart/LineChart.styles.js
  src/components/StackedBarChart/StackedBarChart.styles.js
Labels: bug

#104 Fixes issues with sorting + new data source structure
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/ChartTable.types.js
  src/components/ChartTable/Charts.js
  src/components/ChartTable/Tables.js
Labels: bug, enhancement

#102 issue #99: Encode the cookie value to ensure browser compatibility
  src/components/CookieBanner/CookieBanner.js
  src/pages/Cookies/Cookies.js
Labels: bug

#105 Update About.js
  src/pages/About/About.js
Labels: documentation

#108 Adds feature: Announcements
  src/components/Announcement/Announcement.js
  src/components/Announcement/Announcement.style.js
  src/components/Announcement/Announcement.types.js
  src/components/Announcement/index.js
  src/pages/Regional/Regional.js
Labels: enhancement

#109 Essential updates
  package.json
  src/components/Announcement/Announcement.js
  src/components/Announcement/Announcement.style.js
  src/components/Announcement/Announcement.types.js
  src/components/Announcement/index.js
  src/pages/About/About.js
  src/pages/Regional/Regional.js
Labels: Correction, enhancement

#110 Padding and max height
  src/pages/MobileRegionTable/MobileRegionTable.styles.js
Labels: accessibility, bug

#107 Fix page width
  src/index.scss
Labels: bug

#114 Timed deployment and Markdown for the about page
  package.json
  src/components/ChartTable/ChartTable.js
  src/index.scss
  src/pages/About/About.js
  src/pages/About/About.types.js
  src/pages/Regional/Regional.js
  yarn.lock
Labels: documentation, enhancement

#118 Archives
  src/App.js
  src/components/ChartTable/ChartTable.types.js
  src/components/ChartTable/Tables.js
  src/pages/About/About.styles.js
  src/pages/Archive/Archive.js
  src/pages/Archive/Archive.style.js
  src/pages/Archive/Archive.types.js
  src/pages/Archive/index.js
  src/pages/Regional/Regional.js
Labels: enhancement

#119 About page
  package.json
  src/index.scss
  src/pages/About/About.js
  src/pages/About/About.styles.js
  yarn.lock
Labels: enhancement

#121 New features and essential updates
  package.json
  src/App.js
  src/components/Announcement/index.js
  src/components/ChartTable/ChartTable.js
  src/components/ChartTable/ChartTable.types.js
  src/components/ChartTable/Tables.js
  src/index.scss
  src/pages/About/About.js
  src/pages/About/About.styles.js
  src/pages/About/About.types.js
  src/pages/Archive/Archive.js
  src/pages/Archive/Archive.style.js
  src/pages/Archive/Archive.types.js
  src/pages/Archive/index.js
  src/pages/MobileRegionTable/MobileRegionTable.styles.js
  src/pages/Regional/Regional.js
  yarn.lock
Labels: bug, enhancement

#120 Use `$govuk-font-family` across the service
  src/components/BarChart/BarChart.js
  src/components/BigNumber/BigNumber.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/LineChart/LineChart.js
  src/components/PageTitle/PageTitle.js
  src/components/PageTitle/PageTitle.styles.js
  src/components/StackedBarChart/StackedBarChart.js
  src/index.scss
Labels: bug, enhancement

#117 Always display last tick label on x axis
  src/App.js
  src/components/BarChart/BarChart.js
  src/components/ChartTable/ChartTable.js
  src/components/ChartTable/Tables.js
  src/components/CookieBanner/CookieBanner.js
  src/components/LineChart/LineChart.js
  src/components/RegionTable/RegionTable.styles.js
  src/components/StackedBarChart/StackedBarChart.js
Labels: bug, enhancement

#123 Chart label colours
  src/components/BarChart/BarChart.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/LineChart/LineChart.js
  src/components/StackedBarChart/StackedBarChart.js
Labels: accessibility

#127 Essential updates and fixes
  README.md
  package.json
  src/App.js
  src/components/BarChart/BarChart.js
  src/components/BigNumber/BigNumber.js
  src/components/BigNumber/BigNumber.styles.js
  src/components/CategoricalBarChart/CategoricalBarChart.js
  src/components/ChartTable/ChartTable.js
  src/components/ChartTable/Tables.js
  src/components/CookieBanner/CookieBanner.js
  src/components/LineChart/LineChart.js
  src/components/PageTitle/PageTitle.js
  src/components/PageTitle/PageTitle.styles.js
  src/components/RegionTable/RegionTable.styles.js
  src/components/StackedBarChart/StackedBarChart.js
  src/index.scss
  src/pages/Archive/Archive.js
Labels: accessibility, bug, enhancement

#126 Markdown integration for the Accessibility page
  src/index.scss
  src/pages/Accessibility/Accessibility.js
  src/pages/Accessibility/Accessibility.styles.js
  src/pages/Accessibility/Accessibility.types.js
Labels: accessibility, enhancement
