Repository UKHSA-Internal/coronavirus-dashboard, pull requests merged in 2021-06, with the labels that each got.

#358 Fix .NET casing
  README.md
Labels: Correction

#370 Plotly sample
  package.json
  src/components/Plotter/BasePlot.js
Labels: bug, dependencies

#373 Cookie page notification + govuk frontend version bump
  package-lock.json
  package.json
  src/pages/Cookies/Cookies.js
  yarn.lock
Labels: enhancement

#386 resolves changes to map - #385
  src/components/Map/Map.js
  src/pages/InteractiveMap/InteractiveMap.js
Labels: enhancement

#393 resolves #392 - data label
  package-lock.json
  src/components/Map/Map.js
Labels: Correction

#394 Housekeeping - LGTM
  src/components/DropdownButton/DropdownButton.js
  src/components/Plotter/Waffle.js
  src/pages/Download/Download.js
Labels: enhancement
