Repository UKHSA-Internal/coronavirus-dashboard, pull requests merged in 2021-05, with the labels that each got.

#354 text addition - resolves #352
  package-lock.json
  package.json
  src/pages/Download/Download.js
Labels: documentation

#356 removes reference to hash - resolves #344
  src/pages/ApiDocs/QueryParameters/Structure.js
Labels: Correction, documentation

#357 Readme spelling correction
  README.md
Labels: Correction
